admin/config/routes.rb
Admin::Engine.routes.draw do


  resources :articles
  resources :activities
  resources :activity_details
  resources :admin_users
  resources :comments
  resources :users

  #resource :session, only: [:new, :create, :destroy]
  root to: 'application#welcome'


end

admin/app/models/admin/application_record.rb
module Admin
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

admin/app/controllers/admin/activities_controller.rb
class Admin::ActivitiesController < Admin::ApplicationController
  include Godmin::Resources::ResourceController

  def redirect_after_create
    activities_path
  end

  private

  def resource_params
    params.require(:activity).permit(:title,
                                     :body,
                                     :user_id,
                                     :difficulty,
                                     :category)
  end
end

admin/app/controllers/admin/activity_details_controller.rb
class Admin::ActivityDetailsController < Admin::ApplicationController
  include Godmin::Resources::ResourceController
end

admin/app/controllers/admin/admin_controller.rb
class Admin::AdminController < Admin::ApplicationController

end

admin/app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    include Godmin::ApplicationController
    include Godmin::Authentication
    include Godmin::Authorization


    def authenticate_admin_user
      authenticate_user!
    end

    def admin_user
      current_user
    end

    def admin_user_signed_in?
      user_signed_in?
    end
  end
end

admin/app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  include Godmin::Resources::ResourceController
end

admin/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::ApplicationController
  include Godmin::Resources::ResourceController


  private

  def resource_service
    service = super
    service.options[:interest_list] = params[:interest_list]
    service
  end

  def resource_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :administrator,
                                 :nickname,
                                 :email,
                                 :password,
                                 :password_confirmation,
                                 :gender,
                                 :date_of_birth,
                                 :interest_list,
                                 :description,
                                 :city,
                                 :image)
  end
end

admin/app/helpers/admin/application_helper.rb
module Admin
  module ApplicationHelper
    def difficulty_color(value)
      case value
        when 1
          'green'
        when 2
          'blue'
        when 3
          'red'
      end
    end
  end
end

admin/app/views/admin/activities/_breadcrumb.html.haml
#breadcrumb
  %ol.breadcrumb
    - if action_name == 'index'
      %li.active
        = @resource_class
    - else
      %li
        = link_to @resource_class, @resource_class
      %li.active
        - if @resource.new_record?
          = t('helpers.submit.create', model: @resource_class.model_name.human)
        - else
          %strong
            = @resource.title
      - if @resource.persisted?
        %li.dropdown.pull-right
          %a{data: {toggle: 'dropdown'}, href: '#', role: 'button'}
            = translate_scoped('actions.label')
            %span.caret
          %ul.dropdown-menu
            - if policy(@resource).show? && action_name != 'show'
              %li
                = link_to translate_scoped('actions.show'), @resource
            - if policy(@resource).edit? && action_name != 'edit'
              %li
                = link_to translate_scoped('actions.edit'), [:edit, @resource]
            - if policy(@resource).destroy?
              %li
                = link_to translate_scoped('actions.destroy'), @resource, method: :delete, |
                  data: { confirm: translate_scoped('actions.confirm_message') }           |

admin/app/views/admin/activities/_form.html.haml
= form_for @resource do |f|
  = f.text_field :title
  = f.text_area :body
  = f.select :user_id, User.all.collect {|p| [ p.name, p.id ] }, {}, data: { behavior: 'select-box' }
  = f.select :difficulty, Activity::VALID_DIFFICULTY_VALUES, {}, data: { behavior: 'select-box' }
  = f.select :category, Activity::VALID_CATEGORIES, {}, data: { behavior: 'select-box' }
  = f.submit

admin/app/views/admin/activities/columns/_activity_details.html.haml
- if resource.activity_details.any?
  %table
    %tr
      %td{style: 'width: 40%;'}
        Attachment
      %td{style: 'width: 30%;'}
        Attachment Type
      %td
        Actions
    - resource.activity_details.each do |activity_detail|
      %tr{data: {recording: {id: activity_detail.id }}}
        %td
          = activity_detail.file_attachment
        %td
          = activity_detail.attachment_type
        %td
          .btn-group.btn-group-sm.pull-right
            = link_to 'View', activity_detail_path(activity_detail),
            class: 'btn btn-default'
            = link_to 'Edit', edit_activity_detail_path(activity_detail),
            class: 'btn btn-default'
            = link_to 'Delete', activity_detail_path(activity_detail),
            class: 'btn btn-danger',
            data: {confirm: 'Are you sure?', method: 'delete'}


.btn-group.btn-group-sm.pull-right
  = link_to 'Create Activity Detail', new_activity_detail_path,
          class: 'btn btn-default'

admin/app/views/admin/activities/columns/_comments.html.haml
- if resource.comments.any?
  %table
    %tr
      %td{style: 'width: 40%;'}
        Comment
      %td{style: 'width: 30%;'}
        User
      %td
        Actions
    -resource.comments.each do |comment|
      %tr{data: {comment: {id: comment.id}}}
        %td
          = comment.body
        %td
          = link_to resource.user.name, user_path(resource.user)
        %td
          .btn-group.btn-group-sm.pull-right
            = link_to 'Edit', edit_comment_path(comment), class: 'btn btn-default'
            = link_to 'Delete', comment_path(comment), class: 'btn btn-danger',
              data: { confirm: 'Are you sure', method: 'delete' }

.btn-group.btn-group-sm.pull-right
  = link_to 'New Comment', new_comment_path,
          class: 'btn btn-default'

admin/app/views/admin/activities/columns/_difficulty.html.haml
- resource.difficulty.times do
  %span.glyphicon.glyphicon-star{style: "color: #{difficulty_color(resource.difficulty)}"}

admin/app/views/admin/activities/columns/_user.html.haml
= resource.user.name

admin/app/views/admin/activity_details/_breadcrumb.html.haml
#breadcrumb
  %ol.breadcrumb
    - if action_name == 'index'
      %li.active
        = @resource_class
    - else
      %li
        = link_to @resource_class, @resource_class
      %li.active
        - if @resource.new_record?
          = t('helpers.submit.create', model: @resource_class.model_name.human)
        - else
          %strong
            = @resource.file_attachment
      - if @resource.persisted?
        %li.dropdown.pull-right
          %a{data: {toggle: 'dropdown'}, href: '#', role: 'button'}
            = translate_scoped('actions.label')
            %span.caret
          %ul.dropdown-menu
            - if policy(@resource).show? && action_name != 'show'
              %li
                = link_to translate_scoped('actions.show'), @resource
            - if policy(@resource).edit? && action_name != 'edit'
              %li
                = link_to translate_scoped('actions.edit'), [:edit, @resource]
            - if policy(@resource).destroy?
              %li
                = link_to translate_scoped('actions.destroy'), @resource, method: :delete, |
                  data: { confirm: translate_scoped('actions.confirm_message') }           |

admin/app/views/admin/activity_details/_form.html.haml
= form_for @resource do |f|
  = f.select :activity_id, Activity.all.collect {|p| [ p.title, p.id ] }, {}, data: { behavior: 'select-box' }
  = f.text_field :file_attachment
  = f.select :attachment_type, ActivityDetail::VALID_TYPE_VALUES, {}, data: { behavior: 'select-box' }
  = f.submit

admin/app/views/admin/activity_details/columns/_activity.html.haml
= [resource.activity.title, "(#{resource.activity.user.name})"].join(' ')

admin/app/views/admin/application/welcome.html.haml
.jumbotron.text-center
  %h3
    Welcome to
    %strong AdventureMap

admin/app/views/admin/comments/_form.html.haml
= form_for @resource do |f|
  = f.text_area :body, label: 'Comment'
  = f.select :user_id, User.all.collect {|p| [ p.name, p.id ] }, {}, data: { behavior: 'select-box' }
  = f.select :activity_id, Activity.all.collect {|p| [ p.title, p.id ] }, {}, data: { behavior: 'select-box' }
  = f.submit

admin/app/views/admin/comments/columns/_activity.html.haml
= resource.activity.title

admin/app/views/admin/comments/columns/_user.html.haml
= resource.user.name

admin/app/views/admin/users/_breadcrumb.html.haml
#breadcrumb
  %ol.breadcrumb
    - if action_name == 'index'
      %li.active
        = @resource_class
    - else
      %li
        = link_to @resource_class, @resource_class
      %li.active
        - if @resource.new_record?
          = t('helpers.submit.create', model: @resource_class.model_name.human)
        - else
          %strong
            = @resource.email
      - if @resource.persisted?
        %li.dropdown.pull-right
          %a{data: {toggle: 'dropdown'}, href: '#', role: 'button'}
            = translate_scoped('actions.label')
            %span.caret
          %ul.dropdown-menu
            - if policy(@resource).show? && action_name != 'show'
              %li
                = link_to translate_scoped('actions.show'), @resource
            - if policy(@resource).edit? && action_name != 'edit'
              %li
                = link_to translate_scoped('actions.edit'), [:edit, @resource]
            - if policy(@resource).destroy?
              %li
                = link_to translate_scoped('actions.destroy'), @resource, method: :delete, |
                  data: { confirm: translate_scoped('actions.confirm_message') }           |

admin/app/views/admin/users/_form.html.haml
= form_for @resource do |f|
  = f.text_field :first_name
  = f.text_field :last_name
  = f.text_field :nickname
  = f.text_field :email
  = f.check_box :administrator
  = f.select :gender, User::VALID_GENDER_VALUES, {}
  = f.date_field :date_of_birth
  = f.text_field :city
  = f.password_field :password
  = f.password_field :password_confirmation
  = f.tags_field :interest_list, label: 'Interests', data: { collection: User::VALID_INTERESTS}, id: 'interests'
  = f.submit


:javascript
  Godmin.Datetimepickers.initializeDatepicker($('#user_date_of_birth'), {
    format: 'YYYY-MM-DD',
    defaultDate: '1990-01-01'
  });

  Godmin.Tags.initializeTagger($('#interests'), {
    // disables adding new interests
    //create: false
  });

admin/app/views/admin/users/show.html.haml
= render partial: 'breadcrumb'
%table.table.table-striped
  - @resource_service.attrs_for_show.each do |attr|
    %tr
      %th
        - if attr == :image && @resource.image
          = image_tag(@resource.image)
          %td
        - else
          = @resource_class.human_attribute_name(attr)
          %td= column_value(@resource, attr)

admin/app/views/layouts/godmin/application.html.haml
- content_for :body do
  %nav.navbar.navbar-default.navbar-static-top{role: 'navigation'}
    .container
      .navbar-header
        %button.navbar-toggle.collapsed{aria: {expanded: 'false'}, data: {target: '#godmin-navbar-collapse', toggle: 'collapse'}, type: 'button'}
          %span.sr-only Toggle navigation
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to 'AdventureMap', admin.root_path, class: 'navbar-brand'
      #godmin-navbar-collapse.collapse.navbar-collapse
        %ul.nav.navbar-nav
          = render partial: File.join(engine_wrapper.namespaced_path, 'shared/navigation')
        %ul.nav.navbar-nav.navbar-right
          = render partial: File.join(engine_wrapper.namespaced_path, 'shared/navigation_aside')
  .container
    = render 'layouts/godmin/content'
= render 'layouts/godmin/layout'